In [43]:
from nltk.corpus import stopwords 
from sklearn.model_selection import train_test_split
import string
import time
import math

In [44]:
import numpy as np
import os
directory = r"C:\Users\Sparsh Jain\Downloads\20_newsgroups"
folders = [x[0] for x in os.walk(directory)]
folders = np.array(folders)
folders=folders[1:]

In [45]:
folders

array(['C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\alt.atheism',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\comp.graphics',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\comp.os.ms-windows.misc',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\comp.sys.ibm.pc.hardware',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\comp.sys.mac.hardware',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\comp.windows.x',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\misc.forsale',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\rec.autos',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\rec.motorcycles',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\rec.sport.baseball',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\rec.sport.hockey',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\sci.crypt',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\sci.electronics',
       

In [46]:
files = [x[2] for x in os.walk(directory)]    
files = np.array(files)
files = files[1:]
for i in range(len(files)):
    files[i] = np.array(files[i])

In [47]:
files

array([array(['49960', '51060', '51119', '51120', '51121', '51122', '51123',
       '51124', '51125', '51126', '51127', '51128', '51129', '51130',
       '51131', '51132', '51133', '51134', '51135', '51136', '51137',
       '51138', '51139', '51140', '51141', '51142', '51143', '51144',
       '51145', '51146', '51147', '51148', '51149', '51150', '51151',
       '51152', '51153', '51154', '51155', '51156', '51157', '51158',
       '51159', '51160', '51161', '51162', '51163', '51164', '51165',
       '51166', '51167', '51168', '51169', '51170', '51171', '51172',
       '51173', '51174', '51175', '51176', '51177', '51178', '51179',
       '51180', '51181', '51182', '51183', '51184', '51185', '51186',
       '51187', '51188', '51189', '51190', '51191', '51192', '51193',
       '51194', '51195', '51196', '51197', '51198', '51199', '51200',
       '51201', '51202', '51203', '51204', '51205', '51206', '51207',
       '51208', '51209', '51210', '51211', '51212', '51213', '51214',
       '51215

In [48]:
dictionary = {}
for i in range(len(folders)):
    dictionary[folders[i]] = files[i]

In [49]:
dictionary

{'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\alt.atheism': array(['49960', '51060', '51119', '51120', '51121', '51122', '51123',
        '51124', '51125', '51126', '51127', '51128', '51129', '51130',
        '51131', '51132', '51133', '51134', '51135', '51136', '51137',
        '51138', '51139', '51140', '51141', '51142', '51143', '51144',
        '51145', '51146', '51147', '51148', '51149', '51150', '51151',
        '51152', '51153', '51154', '51155', '51156', '51157', '51158',
        '51159', '51160', '51161', '51162', '51163', '51164', '51165',
        '51166', '51167', '51168', '51169', '51170', '51171', '51172',
        '51173', '51174', '51175', '51176', '51177', '51178', '51179',
        '51180', '51181', '51182', '51183', '51184', '51185', '51186',
        '51187', '51188', '51189', '51190', '51191', '51192', '51193',
        '51194', '51195', '51196', '51197', '51198', '51199', '51200',
        '51201', '51202', '51203', '51204', '51205', '51206', '51207',
        '512

In [50]:
all_list = []
target = []
for i in range(len(folders)):
    for j in range(len(files[i])):
        all_list.append(folders[i] + "\\" + dictionary[folders[i]][j])
        target.append(i)
x = np.array(all_list)
target = np.array(target)

In [51]:
x

array(['C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\alt.atheism\\49960',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\alt.atheism\\51060',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\alt.atheism\\51119',
       ...,
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\talk.religion.misc\\84568',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\talk.religion.misc\\84569',
       'C:\\Users\\Sparsh Jain\\Downloads\\20_newsgroups\\talk.religion.misc\\84570'],
      dtype='<U75')

In [52]:
target

array([ 0,  0,  0, ..., 19, 19, 19])

In [53]:
x_train,x_test,y_train,y_test = train_test_split(x,target,test_size=0.2,random_state=1)

In [54]:
x_train.shape , y_train.shape

((15997,), (15997,))

In [55]:
x_test.shape , y_test.shape

((4000,), (4000,))

In [56]:
np.unique(y_test,return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([215, 201, 201, 204, 203, 224, 196, 170, 227, 205, 192, 202, 198,
        190, 195, 191, 196, 201, 176, 213], dtype=int64))

In [57]:
punc = string.punctuation
punc = punc + '0123456789'

In [58]:
def remove_punctuations_from_list(list):
    for i in range(len(list)):
        temp = ""
        for j in list[i]:
            if(j not in punc):
                temp += j
        list[i] = temp
    return list

In [59]:
stop_words = stopwords.words('english')
stop_words = remove_punctuations_from_list(stop_words)
stop_words.append("")

In [60]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~0123456789'

In [61]:
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 'youre',
 'youve',
 'youll',
 'youd',
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 'shes',
 'her',
 'hers',
 'herself',
 'it',
 'its',
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 'thatll',
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'fe

In [62]:
def remove_punctuations(filepath):
    word_list = open(filepath).read().lower().split()
    for i in range(len(word_list)):
        temp = ""
        for j in word_list[i]:
            if(j not in punc):
                temp+=j
        word_list[i] = temp
    return word_list

In [63]:
def remove_stop_words(np_list):    
    temp = []
    for i in np_list:
        if(i not in stop_words):
            temp.append(i)
    return temp

In [64]:
def clean(filepath):
    np_list = remove_punctuations(filepath)
    cleaned_list = remove_stop_words(np_list)
    return cleaned_list

In [65]:
def dictionary_file(filepath):
    cleaned_list = clean(filepath)
    unique_list = np.unique(cleaned_list, return_counts=True)
    dic = {}
    for i in range(len(unique_list[0])):
        dic[unique_list[0][i]] = unique_list[1][i]
    return dic

In [66]:
def create_path_dictionary():
    dic = {}
    for i in range(20):
        dic[i] = []
    for i in range(len(x_train)):
        dic[y_train[i]].append(x_train[i])
    return dic

In [67]:
def dictionary_folder(path_dict,target_class):
    folder_dic = {}
    for i in range(len(path_dict[target_class])):        
        temp_dic = dictionary_file(path_dict[target_class][i])
        temp_key_list = list(temp_dic.keys())        
        for key in temp_key_list:
            if(key not in folder_dic):
                folder_dic[key] = temp_dic[key]
            else:
                folder_dic[key] += temp_dic[key]
    return folder_dic

In [68]:
def create_mega_dictionary():
    path_dict = create_path_dictionary()
    mega_dict = {}
    for i in range(len(path_dict)):
        folder_dic = dictionary_folder(path_dict,i)
        folder_dic = list(folder_dic.items())
        folder_dic = sorted(folder_dic,reverse=True,key=lambda x: x[1])
        mega_dict[i] = dict(folder_dic)
        mega_dict[i]["TOTAL COUNT"] = np.array(list(mega_dict[i].values())).sum()
    return mega_dict

In [69]:
st = time.time()
mega_dict = create_mega_dictionary()
et = time.time()
et-st

23.25189447402954

In [70]:
mega_dict

{0: {'writes': 992,
  'one': 962,
  'altatheism': 882,
  'would': 877,
  'subject': 846,
  'apr': 841,
  'date': 828,
  'lines': 819,
  'god': 804,
  'path': 793,
  'newsgroups': 792,
  'messageid': 785,
  'article': 784,
  'references': 760,
  'organization': 756,
  'people': 740,
  'gmt': 700,
  'say': 685,
  'think': 606,
  'know': 475,
  'like': 452,
  'morality': 418,
  'believe': 395,
  'nntppostinghost': 381,
  'many': 369,
  'even': 366,
  'im': 366,
  'see': 364,
  'objective': 360,
  'atheists': 357,
  'sender': 353,
  'time': 352,
  'university': 351,
  'way': 343,
  'could': 337,
  'well': 330,
  'said': 329,
  'religion': 325,
  'moral': 321,
  'us': 317,
  'good': 315,
  'christian': 312,
  'science': 305,
  'something': 301,
  'make': 296,
  'evidence': 295,
  'jesus': 294,
  'must': 286,
  'may': 282,
  'system': 280,
  'world': 268,
  'atheism': 266,
  'point': 265,
  'fact': 258,
  'true': 254,
  'things': 253,
  'also': 253,
  'years': 247,
  'mean': 246,
  'right': 

In [71]:
def create_vocab(n_words,mega_dict):
    size = len(mega_dict)
    n = math.ceil(n_words/size)
    vocab = {}
    for i in range(size):
        key_list = list(mega_dict[i].keys())
        for j in range(n):
            if(key_list[j] not in vocab):
                vocab[key_list[j]] = mega_dict[i][key_list[j]]
            else:
                vocab[key_list[j]] += mega_dict[i][key_list[j]]
    return vocab

In [72]:
len(create_vocab(30000,mega_dict))

8831

In [73]:
vocab = create_vocab(30000,mega_dict)
vocab

{'writes': 11749,
 'one': 12167,
 'altatheism': 1144,
 'would': 12797,
 'subject': 17204,
 'apr': 15743,
 'date': 16576,
 'lines': 16682,
 'god': 3579,
 'path': 16266,
 'newsgroups': 16327,
 'messageid': 16071,
 'article': 10033,
 'references': 10414,
 'organization': 15805,
 'people': 8105,
 'gmt': 14219,
 'say': 4199,
 'think': 6347,
 'know': 7263,
 'like': 8128,
 'morality': 729,
 'believe': 2935,
 'nntppostinghost': 6862,
 'many': 4058,
 'even': 4601,
 'im': 5307,
 'see': 4452,
 'objective': 714,
 'atheists': 472,
 'sender': 8747,
 'time': 5409,
 'university': 7956,
 'way': 4156,
 'could': 4952,
 'well': 4741,
 'said': 3475,
 'religion': 966,
 'moral': 653,
 'us': 4882,
 'good': 4990,
 'christian': 1303,
 'science': 2024,
 'something': 3056,
 'make': 4103,
 'evidence': 1306,
 'jesus': 1550,
 'must': 2456,
 'may': 5943,
 'system': 4730,
 'world': 3529,
 'atheism': 301,
 'point': 2537,
 'fact': 2101,
 'true': 1876,
 'things': 2483,
 'also': 6085,
 'years': 2798,
 'mean': 1651,
 'righ

In [74]:
def calculate_class_probs():
    unique = np.unique(y_train,return_counts=True)
    target_class = unique[0]
    count = unique[1]
    probs = []
    for i in range(len(count)):
        temp = math.log10(count[i]/count.sum())
        probs.append(temp)
    return probs

In [75]:
def word_prob(word,target_class,vocab):
    if(word in mega_dict[target_class]):
        numerator = mega_dict[target_class][word] + 1
    else:
        numerator = 1
    denominator = mega_dict[target_class]["TOTAL COUNT"] + len(vocab)
    prob = numerator/denominator
    log_prob = math.log10(prob)
    return log_prob

# def word_prob(word, target_class, vocab, n_words=3000):
#     key_list = list(mega_dict[target_class].keys())
#     for i in range(n_words):
#         if(i==len(key_list)):
#             break
#         if(key_list[i] == word):
#             numerator = mega_dict[target_class][word] + 1
#             break
#         else:
#             numerator = 1    
#     denominator = mega_dict[target_class]["TOTAL COUNT"] + len(vocab)
#     prob = numerator/denominator
#     log_prob = math.log10(prob)
#     return log_prob

In [76]:
def step_predict(filepath, target_class, vocab):
    cleaned_list = clean(filepath)
    score = 0
    for i in cleaned_list:
        score+= word_prob(i,target_class,vocab) 
    return score

In [77]:
def predict(x_test,vocab):
    class_probs = calculate_class_probs()
    pred = []
    for i in x_test:
        final_probs = []
        for j in range(len(class_probs)):
            score = step_predict(i,j,vocab)
            score +=class_probs[j]
            final_probs.append(score)
            maxi = 0
        for j in range(len(class_probs)):
            if(final_probs[j]>final_probs[maxi]):
                maxi = j
        pred.append(maxi)
    return pred

In [78]:
st = time.time()
y_pred = predict(x_test,vocab)
et = time.time()
et-st

94.16830158233643

In [79]:
len(y_pred), y_test.shape

(4000, (4000,))

In [80]:
def score(y_pred , y_true):
    true_arr = y_pred == y_true
    score = true_arr.sum()/len(true_arr)*100
    return score

In [81]:
score(y_pred,y_test)

90.575

In [82]:
np.unique(y_pred==y_test,return_counts=True)

(array([False,  True]), array([ 377, 3623], dtype=int64))

In [83]:
3623/4000*100

90.575

In [84]:
# sklearn Implementation

# from sklearn.naive_bayes import MultinomialNB

# xt = []
# for i in x_train:
#     xt.append(open(i).read())

# xt = np.array(xt)

# xt = xt.reshape((15997,1))

# xt.shape

# clf = MultinomialNB()
# clf.fit(xt,y_train)